### ISSUE TITLE
Ticketsystem says: Eintrag nicht gefunden

### ISSUE THREAD

**Issue by statnmap** [Intera/redmine_time_logging_app#1]
Hi,
I just installed your plugin.
When I click on "Time-logging" in the top menu, a new tab opens and I have this pop-up windows saying:

> Ticketsystem says:
> Eintrag nicht gefunden

My redmine configuration is the following:
Environment:
  Redmine version                3.3.2.stable.16343
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

I run redmine on my own laptop on localhost
I have a user "redmine" on my system
My database is named redmine_default

PS1: On my redmine installation, "enable rest web service" is under "Administration" -> "Settings" -> "API"

**Comment by jkalbhenn** [comment]
hi,
i was not able to reproduce it so far. but i figured out that it is probably a "404 not found" response for one of the background requests when the app initialises. it may have something to do with rails routes.

can you find the url of the request that fails?

in the most up to date version in the master branch i extended the error message to include the url that failed to load.

**Comment by statnmap** [comment]
Hi,
It is not looking at the right place.

> Redmine says:
A request lead to a "404 not found" server response.
relevant url: "http://localhost/time_logging_app/get_csrf_token"

I installed redmine on my current laptop but your plugin should look into redmine plugin path and not root...
Maybe a misconfiguration from me with relative path or so ?

**Comment by jkalbhenn** [comment]
i will look into it.

the url might be correct, mine is "http://localhost:3000/time_logging_app/get_csrf_token".

if redmines root is not "http://localhost/" but "http://localhost/somewhere-else/..." then the issue might be in the routes or the frontend apps code.

**Comment by statnmap** [comment]
My redmine root is: "http://localhost/redmine/" because I have other web programs installed...
I declared it in the "Settings" > "General" > "Host name and path", but it does not change anything for your app.

One day, I will probably have to do a clean install of redmine because I did so many changes to be able to include gitweb and so on... But the installation was so a pain, I do not know if I'll take time to do it.

**Comment by jkalbhenn** [comment]
it should work now, i have updated the plugin.

it was a bug in the plugin, as it has never been tested with redmine not being under "/".

i know setting up redmine can be problematic, so just in case here a few notes about that:
i find it is easiest to have it as a separately running program with its own server (for example puma or webrick for testing. puma can be included as a gem and redmine can be started with something like `RAILS_ENV=production bundle exec rails server puma`) and a reverse proxy (configured in nginx, apache, etc).

if it is in a sub-path then, only one line in "config/environment.rb" is needed, for example:
`RedmineApp::Application.routes.default_scope = "/redmine"`

this is what i did to test the sub-path in the url.

**Comment by statnmap** [comment]
Ok it works. Great.
Thanks for suggestion.
I'll open a new issue but as a suggestion...
