### ISSUE TITLE
Time log

### ISSUE THREAD

**Issue by statnmap** [Intera/redmine_time_logging_app#4]
Hi,
I would enjoy to have a time logger that count alone the time I spent on the different project.
I know that 'toggl' is interfaced with redmine, but I do not want a third-party to store my data somewhere.
Currently, I am using 'gtimelog' on Ubuntu, but then I have to re-enter manually my timelog on redmine. Even if it is now quicker with your plugin...
I can see difficulties:
- It should allow breaks, not recorded in redmine
- It should continue to work even if the session/computer is stopped during the day.

Well, I do not know if you ever planned to do this...
If not, you can close this issue. I'll find a way to fill in redmine database with the text file from gtimelog...

**Comment by jkalbhenn** [comment]
i think that is a good idea. it has been considered before, but i have always felt that it is too easy to forget starting/stopping the timer on breaks or task switches and wanted to first maybe find a solution that helps with that. but now i guess a simple implementation would already be useful.

as a first simple idea, there could be a new start/pause button at the top right, and the currently elapsed time could be displayed directly in the hour/minute fields. this could be used for new time entries as well as for continuing existing time entries.

> It should allow breaks, not recorded in redmine.

a button to start/pause the timer is perhaps sufficient for this.

> It should continue to work even if the session/computer is stopped during the day.

if i understand this correctly, that would mean the timer runs even when the browser is closed or the computer is shut down. there could be a redmine setting saying if the timer should behave like that. and then there should probably be some timeout value or something or it might log infinite time on forgotten issues. but it is a bigger feature that i would need to think about more.

it can take a while until i find the time to implement the time counter.

by the way, i have also seen redmine plugins that count the elapsed time for time logging. maybe these ones, but i think i saw a third one also:
http://www.redmine.org/plugins/bestest_timer
https://github.com/efigence/redmine_hamster
