### ISSUE TITLE
http status 422

### ISSUE THREAD

**Issue by pfreeborn01** [Intera/redmine_time_logging_app#5]
initially I had this working ok on Redmine v4.1.1 on Ubuntu 20.0, but now I am getting "http status 422" errors if i try to log hours at project level.  It seems to still work when logging hours to issues.  (I have left the "Disallow logging time on projects" checkbox in plugin options unchecked.)

**Comment by jkalbhenn** [comment]
thanks for the report. i will be able to look into this tomorrow.

**Comment by jkalbhenn** [comment]
i could reproduce this and fix it. only one file changed, [app/controllers/time_logging_app_controller.rb](https://github.com/Intera/redmine_time_logging_app/tree/master/app/controllers), which can be replaced. then restart redmine. please let me know if that solves the issue.

**Comment by pfreeborn01** [comment]
thanks for your quick update -- yes, this works fine now.  (A very nice app too!)
