### ISSUE TITLE
Start and Stop Timer

### ISSUE THREAD

**Issue by SinghNanak** [Intera/redmine_time_logging_app#6]
Add buttons to start and stop timer. also add a icon on menu bar so user can see that the timer is running if they hover on the icon show all the issue timer running by clicking them they can open it and submit.

**Comment by jkalbhenn** [comment]
A basic timer feature has now been implemented.
There is a new play button in the top right. When pressed, a timer starts and the elapsed time is displayed in the tab title. When pressing the play (now stop) button again, the elapsed time will be added.

**Comment by SinghNanak** [comment]
thank you for the update. I will check it out
